Repository AY2223S1-CS2103T-T11-1/tp, pull requests merged in 2022-10, with the labels that each got.

#36 Add Tasks to model
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/item/DisplayItemList.java
  src/main/java/seedu/address/model/item/exceptions/DuplicateItemException.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/UniqueTaskList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: enhancement, priority.High

#39 Add Fields to Contacts
  src/main/java/seedu/address/logic/commands/AddFieldCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemoveFieldCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddFieldCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FieldPrefixes.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/Prefix.java
  src/main/java/seedu/address/logic/parser/RemoveFieldCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Fields.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/person/field/Field.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: enhancement, priority.Medium

#48 Update Developer Guide for Model Class and UI Class
  docs/DeveloperGuide.md
  docs/diagrams/GenerateCardSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UpdateDetailPanel.puml
  docs/diagrams/style.puml
  docs/images/GenerateCardSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/UpdateDetailPanel.png
  src/main/java/seedu/address/ui/GroupCard.java
  src/main/java/seedu/address/ui/GroupListPanel.java
  src/main/java/seedu/address/ui/TaskListPanel.java
Labels: documentation, type.DeveloperGuide

#49 Update Developer Guide for Custom Fields Implementation
  docs/DeveloperGuide.md
  docs/diagrams/AddFieldSequenceDiagram.puml
  docs/images/AddFieldSequenceDiagram.png
Labels: documentation, type.DeveloperGuide

#56 Improve Task command keywords
  src/main/java/seedu/address/logic/commands/tasks/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/tasks/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/tasks/MarkTaskCommand.java
  src/main/java/seedu/address/logic/commands/tasks/TaskCommand.java
  src/main/java/seedu/address/logic/commands/tasks/UnmarkTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/main/java/seedu/address/logic/parser/RmTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/UnmarkCommandParser.java
  src/main/java/seedu/address/logic/parser/tasks/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/tasks/DeleteTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/tasks/MarkTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/tasks/TaskCommandParser.java
  src/main/java/seedu/address/logic/parser/tasks/UnmarkTaskCommandParser.java
Labels: enhancement, priority.High

#68 test
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/tasks/ProgressCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/tasks/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/tasks/ProgressCommandParser.java
  src/main/java/seedu/address/logic/parser/tasks/TaskCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/attribute/AbstractAttribute.java
  src/main/java/seedu/address/model/attribute/Progress.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/item/AbstractContainerItem.java
  src/main/java/seedu/address/model/item/AbstractDisplayItem.java
  src/main/java/seedu/address/model/item/AbstractSingleItem.java
  src/main/java/seedu/address/model/item/DisplayItem.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tag/UniqueID.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/storage/JsonAdaptedGroup.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  unused/AbstractContainerItem
Labels: enhancement

#61 Integrate Attribute with Person, Task and Group
  src/main/java/seedu/address/logic/commands/AddFieldCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemoveFieldCommand.java
  src/main/java/seedu/address/logic/commands/attributes/AddAttributeCommand.java
  src/main/java/seedu/address/logic/commands/attributes/AddGroupAttributeCommand.java
  src/main/java/seedu/address/logic/commands/attributes/AddPersonAttributeCommand.java
  src/main/java/seedu/address/logic/commands/attributes/AddTaskAttributeCommand.java
  src/main/java/seedu/address/logic/commands/attributes/EditAttributeCommand.java
  src/main/java/seedu/address/logic/commands/attributes/EditGroupAttributeCommand.java
  src/main/java/seedu/address/logic/commands/attributes/EditPersonAttributeCommand.java
  src/main/java/seedu/address/logic/commands/attributes/EditTaskAttributeCommand.java
  src/main/java/seedu/address/logic/commands/attributes/RemoveAttributeCommand.java
  src/main/java/seedu/address/logic/commands/attributes/RemoveGroupAttributeCommand.java
  src/main/java/seedu/address/logic/commands/attributes/RemovePersonAttributeCommand.java
  src/main/java/seedu/address/logic/commands/attributes/RemoveTaskAttributeCommand.java
  src/main/java/seedu/address/logic/parser/AddAttributeCommandParser.java
  src/main/java/seedu/address/logic/parser/AddFieldCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditAttributeCommandParser.java
  src/main/java/seedu/address/logic/parser/RemoveAttributeCommandParser.java
  src/main/java/seedu/address/logic/parser/RemoveFieldCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/attribute/AbstractAttribute.java
  src/main/java/seedu/address/model/attribute/Attribute.java
  src/main/java/seedu/address/model/attribute/AttributeList.java
  src/main/java/seedu/address/model/attribute/exceptions/AttributeException.java
  src/main/java/seedu/address/model/attribute/exceptions/AttributeNotFoundException.java
  src/main/java/seedu/address/model/attribute/exceptions/DuplicateAttributeException.java
  src/main/java/seedu/address/model/group/exceptions/GroupOutOfBoundException.java
  src/main/java/seedu/address/model/item/AbstractDisplayItem.java
  src/main/java/seedu/address/model/item/DisplayItem.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/person/exceptions/PersonOutOfBoundException.java
  src/main/java/seedu/address/model/task/exceptions/TaskOutOfBoundException.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: enhancement, priority.High

#69 Edit DevGuide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/TaskClassDiagram.png
Labels: documentation, type.DeveloperGuide, type.UserGuide

#146 User guide update
  docs/UserGuide.md
  docs/images/AliasingCommandUi
  docs/images/ContactmationUi.png
  docs/images/ContactmationUiClean.png
  docs/images/ContainsCommandUi
  docs/images/CustomCommandUi1
  docs/images/CustomCommandUi2
  docs/images/ForeachCommandUi
  docs/images/MultipleCommandsUi
  docs/images/SelectCommandUi
  src/main/resources/view/MainWindow.fxml
Labels: documentation, type.UserGuide
